# Generated by Django 4.0 on 2024-11-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCard',
        ),
    ]
